import { styles } from "../style";
import { CarCanvas } from "./canvas";

const Hero = () => {
  return (
    <section className="relative w-full h-[150vh] mx-auto">
      <div
        className={`${styles.paddingX} absolute inset-0  max-w-7xl mx-auto flex flex-col  justify-start items-center gap-5`}
      >
        <div className="flex flex-col justify-center items-center mt-[20rem]">
          {/* <div className="w-5 h-5 rounded-full bg-[#ed2546]"></div>
          <div className="w-1 sm:h-80 h-40  bg-gradient-to-b from-[#ed2546]"></div> */}
          <h1 className={`${styles.heroHeadText}`}>
            Hi, I'm <span className="text-[#ed2546] ">Tomasi</span>
          </h1>
        </div>
        <div className="">
          {/* <h1 className={`${styles.heroHeadText}`}>
            Hi, I'm <span className="text-[#ed2546] ">Tomasi</span>
          </h1> */}
          <p className={`${styles.heroSubText}`}>
            This background was generated by my AI assistant
          </p>
        </div>
      </div>
      <CarCanvas />
    </section>
  );
};

export default Hero;
